---
development:
  dialect: postgres
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/todoapp_development?sslmode=disable"}}
  pool: {{envOr "DATABASE_POOL_SIZE" "5"}}

test:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/todoapp_test?sslmode=disable"}}
  pool: {{envOr "DATABASE_POOL_SIZE" "5"}}

integration:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/todoapp_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/todoapp_production?sslmode=disable"}}
