name: Tests
on: [push]
jobs:
  Test:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_HOST: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        stable: false
        go-version: '1.16.3'
      id: go
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go

    - name: Buffalo Tests
      env:
        SHARED_CAS_USER: $SHARED_CAS_AUTH_TOKEN
        SHARED_CAS_AUTH_TOKEN: $SHARED_CAS_USER
        GOPROXY: "https://proxy.golang.org"
        GO111MODULE: "on"
        DATABASE_URL: "postgres://postgres:postgres@127.0.0.1:${{ job.services.postgres.ports[5432] }}/todoapp_test?sslmode=disable"
        GO_ENV: test
      run: |
        go get -u -v github.com/gobuffalo/buffalo/buffalo
        buffalo test ./...
        

    - name: Milo
      run: |
        curl -sf https://gobinaries.com/wawandco/milo/cmd/milo | sh
        milo review ./templates